name: Publish distribution to PyPI

on:
    release:
        types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build distribution
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies/build
      run: >-
        pip install poetry &&
        poetry install &&
        poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publishing Python distibution to PyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/ya-business-api

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publishing distibution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
